FROM 298801546701.dkr.ecr.eu-west-1.amazonaws.com/liveobs:__VERSION__

USER root
ADD coverage.sh /opt/odoo/coverage.sh
RUN chmod +x /opt/odoo/coverage.sh
RUN apt-get update
RUN apt-get install s3cmd -y --no-install-recommends
