---
# NH AWS EC2 NHC Coverage play

- hosts: "tag_nhj_id_{{ nhj_id }}"
  user: root

  vars_files:
    - ../../nh-ansible/roles/nh-nhc-deploy/defaults/main.yml # Include vars from nh-odoo role

  roles:
      - nh-nhc-deploy