---
# NH AWS EC2 Launcher Play
# Launches the NH-Base-C6.6 AMI - Prepares as NH-Core

- hosts: localhost
  connection: local
  gather_facts: False

  vars:
    keypair: NH-Deploy-EU
    ami_id: ami-5cc3922b

  tasks:
    - name: Launch new Instance
      ec2:
          key_name: NH-Deploy-EU
          group: NH-openeobs-sg-EU
          instance_type: t2.medium
          region: eu-west-1
          image: "{{ami_id}}"
          wait: true
          instance_tags:
             name: "NH-Base-{{ jbuild }}"
             class: NH-Base
             nh_jbref: "{{ jbuild }}"
      register: ec2

    - name: Add all instance public IPs to host group
      add_host: hostname={{ item.public_ip }} groups=ec2deploy
      with_items: ec2.instances

    - name: Wait for SSH to come up
      wait_for: host={{ item.public_dns_name }} port=22 delay=60 timeout=320 state=started
      with_items: ec2.instances

- hosts: ec2deploy
  name: Prepare NH-Core
  user: root
  gather_facts: True
  tasks:
    - name: Install epel-release # Install EPEL
      yum: name=epel-release state=installed
    - name: Update all packages
      yum: name=* state=latest
    - name: Install env deps
      yum: name={{ item }} state=installed
      with_items:
         - wget
         - openssh-clients
         - vim
         - nmap
         - tmux
         - zip
         - unzip
         - git
         - libselinux-python
