---
# NH AWS EC2 Example Annotated Play
# Launches the NH-Base-C6.6 AMI - Prepares as NH-Core

- hosts: localhost
  connection: local
  gather_facts: False

  vars:
    keypair: NH-Deploy-EU
    ami_id: ami-5cc3922b

  tasks:
    - name: Launch new Instance
      ec2:
          key_name: NH-Deploy-EU
          group: NH-openeobs-sg-EU
          instance_type: t2.medium
          region: eu-west-1
          image: "{{ami_id}}"
          wait: true
          ## Could ensure multiple running instances based on tags
          # exact_count: 2
          # count_tag:
          #    class: Demo-Ready
          instance_tags:
             ## List of tags to add to the instance on create
             name: "NH-odoo-{{ jbuild }}"
             class: "NH-odoo-{{ odoo_tag }}"
             # nh_aws_p_createdb: "{{ odoo_inv_createdb }}"
             # nh_aws_p_odoo_tag: "{{ odoo_tag }}"
             # nh_aws_p_nhc_ver: "{{ version }}"
             nh_jbref: "{{ jbuild }}"
      register: ec2

    - name: Add all instance public IPs to host group
      add_host: hostname={{ item.public_ip }} groups=ec2deploy
      with_items: ec2.instances

    - name: Wait for SSH to come up
      wait_for: host={{ item.public_dns_name }} port=22 delay=60 timeout=320 state=started
      with_items: ec2.instances

    ## Register this host in Route 53
    # - name: Register in route53 DNS name
    #   route53:
    #       command: create
    #       overwrite: true
    #       zone: openeobs.net
    #       record: "{{ openeobs_public_dns }}"
    #       type: A
    #       ttl: 300
    #       value: "{{ item.public_ip }}"
    #   with_items: ec2.instances

## Run some specific tasks on these instances
# - hosts: ec2deploy
#   name: Prepare NH-Core
#   user: root
#   gather_facts: True
#   tasks:
#     - name: Install epel-release # Install EPEL
#       yum: name=epel-release state=installed
#     - name: Update all packages
#       yum: name=* state=latest
#     - name: Install env deps
#       yum: name={{ item }} state=installed
#       with_items:
#          - wget
#          - openssh-clients

## Apply some specific roles on these instances

# - hosts: ec2deploy
#   name: Prepare NH-DevReady
#   user: root
#   gather_facts: True

  # vars:
  #   - odoo_addons_path: "{{ root_deploy_path }}/odoo-addons"
  #   # - odoo_tag: "{{ ec2_tag_nh_aws_p_odoo_tag }}"
  #   - odoo_start_filepath: "{{ odoo_base_path }}/odoo.py"
  #   - odoo_version: 8
  #   - db_name: nhclinical
  #   - nh_clinical_user: odoo
  #   # - odoo_inv_createdb: "{{ ec2_tag_nh_aws_p_createdb }}"
  #   - odoo_inv_install_uat: "{{ odoo_inv_createdb }}_uat"
  #   # - version: "{{ ec2_tag_nh_aws_p_nhc_ver }}"

#   roles:
#       - nh-dev # Common dependencies for the environment
#       - ntp
#       - python27
#       - virtualenv
#       - postgresql