---
# NH oVirt VM Provisioning play for NHC
# Provisions in readyiness for NHC

- hosts: nh-ovirt-core
  user: root
  gather_facts: True

  roles:
      - nh-default # NH Common defaults (repos, iptables, selinux)
      - python27 # Using Centos SCL https://www.softwarecollections.org
      - virtualenv # Installed to /opt/venv
      - postgresql # v9.3
      - nodejs # 
      - phantomjs # 
      - wkhtml #