---
# NH oVirt VM Provisioning play for NHC
# Provisions NHC with open-eObs

- hosts: nh-ovirt-nhc
  user: root
  gather_facts: True

  vars_files:
    - vars/nh-ovirt-vars-2016.yml

  roles:
      - nginx # configured for NH Clinical
      # - nh-nhc-deploy # NH Clinical + openeObs
      # - nh-demo-deploy
      - nh-deployment