---
# NH AWS EC2 Launcher task
# Based on http://docs.ansible.com/ansible/guide_aws.html

- hosts: localhost
  connection: local
  gather_facts: False

  vars:
    keypair: NH-Deploy-EU
    ami_id: ami-30ff5c47

  tasks:
    - name: Launch new Instance
      ec2:
          key_name: NH-Deploy-EU
          group: NH-openeobs-sg-EU
          instance_type: t2.large
          region: eu-west-1
          image: "{{ami_id}}"
          wait: true
          exact_count: 2
          count_tag:
             Name: Base-Count
          instance_tags:
             Name: Base-Instance
      register: ec2

    - name: Add all instance public IPs to host group
      add_host: hostname={{ item.public_dns_name }} groups=ec2hosts ansible_ssh_private_key_file=~/.ssh/{{ keypair }}.pem
      with_items: ec2.instances

    - name: Wait for SSH to come up
      local_action: wait_for host={{ item.public_dns_name }} port=22 delay=60 timeout=320 state=started
      with_items: ec2.instances


- hosts: ec2hosts
  name: configuration play
  user: root
  gather_facts: true

  vars:
    keypair: NH-Deploy-EU

  tasks:
    - name: Install epel-release # Install EPEL
      yum: name=epel-release state=installed
    - name: Update all packages
      yum: name=* state=latest
    - name: Install env deps
      yum: name={{ item }} state=installed
      with_items:
         - wget
         - openssh-clients
         - vim
         - nmap
         - tmux
         - zip
         - unzip
         - git
         - libselinux-python