---
# NH AWS EC2 Launcher task

- name: Launch an EC2 instance
  hosts: local
  connection: local
  gather_facts: False
  tags: provisioning
  vars_files:
    - nhvault.yml
  vars:
    instance_type: t2.large
    security_group: NH-openeobs-sg
    image: ami-81d092b1
    # image: ami-edb9b4dd
    region: us-west-2
    keypair: NH-Deploy
  tasks:
    - name: Launch new Instance
      local_action: ec2 instance_tags="Name=NHC-AWS" group={{ security_group }} instance_type={{ instance_type}} image={{ image }} wait=true region={{ region }} keypair={{ keypair }}
      register: ec2
    - name: Add instance to local host group
      local_action: lineinfile dest=../inventory/nh-aws regexp="{{ item.public_dns_name }}" insertafter="[launched]" line="{{ item.public_dns_name }} ansible_ssh_private_key_file=~/.ssh/{{ keypair }}.pem"
      with_items: ec2.instances
    - name: Wait for SSH to come up
      local_action: wait_for host={{ item.public_dns_name }} port=22 delay=60 timeout=320 state=started
      with_items: ec2.instances
