---
# NH AWS EC2 Launcher Play
# Launches an 'NHC Ready' NH-Dev-C6.6 AMI ready for nh-nhc-installer.yml

- hosts: localhost
  connection: local
  gather_facts: False

  vars:
    keypair: NH-Deploy-EU
    ami_id: "{{ ami_id }}"

  tasks:
    - name: Launch new Instance
      ec2:
          key_name: NH-Deploy-EU
          group: NH-openeobs-sg-EU
          instance_type: "{{ nh_instance_type }}"
          region: eu-west-1
          image: "{{ ami_id }}"
          wait: true
          instance_tags:
             Name: ci{{ jbuild }}
             class: NHC-Installed
             nh_aws_p_createdb: "{{ odoo_inv_createdb }}"
             nh_aws_p_odoo_tag: "{{ odoo_tag }}"
             nh_aws_p_nhc_ver: "{{ version }}"
             nh_jbref: "{{ jbuild }}"
             nh_ciref: "ci{{ jbuild }}"
             nh_aws_p_fqdn: "{{ openeobs_public_dns }}.aws.openeobs.net"
      register: ec2

    - name: Add all instance public IPs to host group
      add_host: hostname={{ item.public_ip }} groups=ec2deploy
      with_items: ec2.instances

    - name: Wait for SSH to come up
      wait_for: host={{ item.public_dns_name }} port=22 delay=60 timeout=320 state=started
      with_items: ec2.instances

    # - name: Register in route53 DNS name
    #   route53:
    #       command: create
    #       overwrite: true
    #       zone: openeobs.net
    #       record: "{{ openeobs_public_dns }}.aws.openeobs.net"
    #       type: A
    #       ttl: 300
    #       value: "{{ item.public_ip }}"
    #   with_items: ec2.instances
