#!/usr/bin/make

create_addons_dir:
	make -C ${folder} $@

prebuild:
	make -C ${folder} $@

build:
	make -C ${folder} $@

test:
	make -C ${folder} $@

publish:
	make -C ${folder} $@

.PHONY: create_addons_dir prebuild build test publish
