version: '2'
services:
  web:
    environment:
      - GO_PIPELINE_COUNTER=${GO_PIPELINE_COUNTER}
    build:
      context: .
      dockerfile: Dockerfile-testing
    entrypoint: /opt/odoo/createdb.sh
