version: '2'
services:
  web:
    build:
      context: docker
    ports:
      - "8069:8069"
    links:
      - db
    environment:
      # These are picked up in `/entrypoint.sh` which starts the server.
      - USER=odoo
      - PASSWORD=odoo
      - HOST=db
    depends_on:
      - db
    user: odoo
    mem_limit: 600M

  db:
    image: postgres:9.3
    environment:
      - POSTGRES_USER=odoo
      - POSTGRES_PASSWORD=odoo
      - POSTGRES_DB=db
