version: "3"
services:
  app:
    image: 298801546701.dkr.ecr.eu-west-1.amazonaws.com/liveobs:${VERSION}
    ports:
      - "8069:8069"
    environment:
      # These are picked up in `/entrypoint.sh` which starts the server.
      - HOST=db
      - PORT=5432
      - USER=odoo
      - PASSWORD=odoo
    depends_on:
      - db
    user: odoo
    deploy:
      placement:
        constraints:
          - node.labels.type == app

  db:
    image: postgres:9.3
    environment:
      - POSTGRES_USER=odoo
      - POSTGRES_PASSWORD=odoo
      - POSTGRES_DB=db
      # Docker Hub Postgres page recommends overriding data location when using a fs mount.
      - PGDATA=/var/lib/postgresql/data/liveobs
    volumes:
      - data:/var/lib/postgresql/data/liveobs
    deploy:
      placement:
        constraints:
          - node.labels.type == db

  adt-connector:
    image: 298801546701.dkr.ecr.eu-west-1.amazonaws.com/adtconnector:latest
    environment:
      - USER=nhadt
      - PASSWORD=nhadt
      - HOST=db
    depends_on:
      - db
    deploy:
      placement:
        constraints:
          - node.labels.type == int

volumes:
  data:
