---
# NH AWS EC2 Play
# Vars for nh-launch.yml

#nhp_keypair: NH-Deploy-EU
nhp_keypair: nh-vagrant-id
nhp_amiid: ami-9fb41aec # NH Deploy 1451866584
nhp_instancetype: t2.medium
nhp_securitygroup: NH-openeobs-sg-EU
nhp_region: eu-west-1
nhp_prefix: default
nhp_tld: nhtek.io
